# Generated by Django 3.2.9 on 2021-11-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title of message.', max_length=120)),
                ('message', models.TextField(help_text="what's on your mind ...")),
            ],
        ),
        migrations.RemoveField(
            model_name='categories_suggestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='service',
        ),
        migrations.RemoveField(
            model_name='client',
            name='language',
        ),
        migrations.RemoveField(
            model_name='language_translations',
            name='language',
        ),
        migrations.RemoveField(
            model_name='service_faq',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service_faq_docs',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='service_faq_link',
            name='faq_id',
        ),
        migrations.RemoveField(
            model_name='transcript_message',
            name='transcript',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Categories_suggestion',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Language_translations',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Service_faq',
        ),
        migrations.DeleteModel(
            name='Service_faq_docs',
        ),
        migrations.DeleteModel(
            name='Service_faq_link',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
        migrations.DeleteModel(
            name='Transcript_message',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
