# Generated by Django 3.2.9 on 2021-11-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0002_auto_20211124_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='example@gmail.com', help_text='email', max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='full_name',
            field=models.CharField(default='Just_some_name', help_text='full_name', max_length=120),
        ),
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(default='1', help_text='level', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default='Uzumaki07', help_text='password', max_length=255),
        ),
    ]
