# Generated by Django 3.2.9 on 2021-11-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0003_auto_20211125_0014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='UserProfile',
        ),
    ]
