# Generated by Django 3.2.9 on 2021-11-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0004_rename_post_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Post',
        ),
    ]
