# Generated by Django 3.2.9 on 2022-03-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0005_rename_userprofile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.EmailField(help_text='email', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(help_text='password', max_length=255),
        ),
    ]
