# Generated by Django 3.2.9 on 2022-03-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel_api', '0007_alter_post_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_name',
            field=models.CharField(help_text='full_name', max_length=120),
        ),
    ]
